export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const GET_CONTENT = "GET_CONTENT";
export const GET_CONTENT_SUCCESS = "GET_CONTENT_SUCCESS";
export const GET_CONTENT_FAIL = "GET_CONTENT_FAIL";

export const GET_CONTENT_SEARCH = "GET_CONTENT_SEARCH";
export const GET_CONTENT_SEARCH_SUCCESS = "GET_CONTENT_SEARCH_SUCCESS";
export const GET_CONTENT_SEARCH_FAIL = "GET_CONTENT_SEARCH_FAIL";

export const POST_CONTENT = "POST_CONTENT";
export const POST_CONTENT_SUCCESS = "POST_CONTENT_SUCCESS";
export const POST_CONTENT_FAIL = "POST_CONTENT_FAIL";

export const POST_COMMENTS = "POST_COMMENTS";
export const POST_COMMENTS_SUCCESS = "POST_COMMENTS_SUCCESS";
export const POST_COMMENTS_FAIL = "POST_COMMENTS_FAIL";

export const DELETE_CONTENT = "DELETE_CONTENT";
export const DELETE_CONTENT_SUCCESS = "DELETE_CONTENT_SUCCESS";
export const DELETE_CONTENT_FAIL = "DELETE_CONTENT_FAIL";

export const POST_VIEWER = "POST_VIEWER";
export const POST_VIEWER_SUCCESS = "POST_VIEWER_SUCCESS";
export const POST_VIEWER_FAIL = "POST_VIEWER_FAIL";

export const UPDATE_CONTENT = "UPDATE_CONTENT";
export const UPDATE_CONTENT_SUCCESS = "UPDATE_CONTENT_SUCCESS";
export const UPDATE_CONTENT_FAIL = "UPDATE_CONTENT_FAIL";
